jwt:
  secret: stagged

amazonProperties:
  endpointUrl: url
  accessKey: accessKey
  secretKey: secretKey
  bucketName: stagged-images

amazonDynamo:
  endpointUrl: url
  accessKey: accessKey
  secretKey: secretKey
  region: us-west-1


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

zuul:
  #Service will be mapped under the /api URI
  #add the real service instead of test-service
  prefix: /api
  routes:
    test-service:
      path: /test-service/**
      url: http://localhost:8001

